### ISSUE TITLE
Add missing "scripts" directory to the "project directory structure"

### ISSUE THREAD

**Issue by NethmiRodrigo** [neutralinojs/neutralinojs.github.io#192] opened 2022-04-06 15:47 UTC
The project structure of both the framework and client library is missing the "scripts" folder

**Comment by shalithasuranga** [comment] 2022-04-08 10:22
Hey @NethmiRodrigo  yeah sure :tada:

**Comment by shalithasuranga** [comment] 2022-05-01 15:57
Hey.. I am closing this one since the issue is already fixed. Thanks :tada:

**Closed by shalithasuranga** 2022-05-01 15:57 UTC
