### ISSUE TITLE
[Bug] :  style issue : cannot see the text of npm install for library due to text color in light mode

### ISSUE THREAD

**Issue by Adityajparmar37** [neutralinojs/neutralinojs.github.io#327] opened 2024-07-03 17:10 UTC
# ScreenShort of issue: 

![image](https://github.com/neutralinojs/neutralinojs.github.io/assets/105008414/fa114878-55b9-43c5-9ee1-af22bdb37ac4)

# Change to be made

- Change the color of text  in white/light mode

**Comment by sahith-ch** [comment] 2024-07-04 07:21
is the issue still open?

**Comment by shubhiscoding** [comment] 2024-07-06 09:57
Can I work on this?

**Comment by viralgupta** [comment] 2024-07-07 14:46
duplicate of #321

**Comment by shalithasuranga** [comment] 2024-11-09 10:56
Closing as a duplicate of #321. Thanks everyone :tada:

**Closed by shalithasuranga** 2024-11-09 10:56 UTC
